### ISSUE TITLE
同時入力は仕様ですか?

### ISSUE THREAD

**Issue by TOKUSHI-2000** [WAFFLEELFFAW/WAFFLEELFFAW.github.io#5]
表の長袖と半袖同時に入力すると**WF合計が両方の合計になります**これは 仕様ですか?
ページそのものを複数用意することで、内部的に切り替えるようにもできると思いますがどうしますか?

**Comment by WAFFLEELFFAW** [comment]
長袖と半袖を同時に計算できるようにするため仕様です。
お気遣いありがとうございます。
